"""Minimal FastAPI app scaffolded by LeAgent's coding agent.

Routes:
    GET /          → service banner
    GET /health    → liveness probe used by the supervisor
    GET /items     → list items
    POST /items    → append an item
    DELETE /items/{idx} → remove by index

The state is intentionally in-memory so the scaffold has no
database dependency. Replace the ``ITEMS`` list with a real
backend (SQLModel, MongoDB, ...) when the agent extends the app.
"""

from __future__ import annotations

from fastapi import FastAPI, HTTPException, status
from pydantic import BaseModel, Field

app = FastAPI(
    title="LeAgent FastAPI scaffold",
    version="0.1.0",
    description="Generated by the LeAgent coding agent.",
)


class Item(BaseModel):
    name: str = Field(..., min_length=1, max_length=120)
    quantity: int = Field(default=1, ge=0)


ITEMS: list[Item] = [Item(name="hello", quantity=1)]


@app.get("/", tags=["root"])
def root() -> dict[str, str]:
    return {
        "service": "LeAgent FastAPI scaffold",
        "docs": "/docs",
        "health": "/health",
    }


@app.get("/health", tags=["health"])
def health() -> dict[str, bool | str]:
    return {"ok": True, "status": "ready"}


@app.get("/items", tags=["items"])
def list_items() -> list[Item]:
    return list(ITEMS)


@app.post("/items", status_code=status.HTTP_201_CREATED, tags=["items"])
def add_item(item: Item) -> Item:
    ITEMS.append(item)
    return item


@app.delete("/items/{index}", tags=["items"])
def remove_item(index: int) -> dict[str, int]:
    if index < 0 or index >= len(ITEMS):
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Item index out of range",
        )
    ITEMS.pop(index)
    return {"remaining": len(ITEMS)}
